apiVersion: v1
data:
  one.yaml: |+
    - name: command1
      command: ["/path/to/command1", "param1", "param2"]
      schedule:
        every: "2:30"
        between:
          - 3:0-6
          - 12-17:25
        months:
          - jun
          - 3
          - dec
        weekdays:
          - wed
          - mon
          - tue
        monthdays:
          - 13
        at:
          - 3:00
          - 5:13
          - 15:34
        except:
          weekdays:
            - wed
            - tue
          monthdays:
            - 13
          at:
            - 5

    - name: command2
      command: ["/path/to/command2"]
      schedule:
        every: 2:30
        weekdays:
          - wed
          - mon
          - tue
        monthdays:
          - 13
        at:
          - 3:0
          - 5
          - 15:19
        except:
          weekdays:
            - wed
            - tue
          monthdays:
            - 13
          at:
            - 5

kind: ConfigMap
metadata:
  creationTimestamp: 2019-07-20T07:54:48Z
  name: schedule
  namespace: default
  resourceVersion: "336522"
  selfLink: /api/v1/namespaces/default/configmaps/schedule
  uid: a5ab2a27-aac3-11e9-9e69-025000000001
